default_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
default_list:
    path:     /list
    defaults: { _controller: AppBundle:Default:list }
default_form:
    path:     /form
    defaults: { _controller: AppBundle:Default:form }
concert_delete:
    path:     /concert/delete/{id}
    defaults: { _controller: AppBundle:Default:delete }
