default_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
default_list:
    path:     /list
    defaults: { _controller: AppBundle:Default:list }
default_form:
    path:     /form
    defaults: { _controller: AppBundle:Default:form }
suggest_query:
    path:     /suggest/{type}/{value}
    defaults: { _controller: AppBundle:Suggest:index }
