app_ville:
    resource: "@AppBundle/Resources/config/routing/ville.yml"
    prefix:   /ville

ville_default:
    path:     /
    defaults: { _controller: AppBundle:Ville:index }

default_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
default_list:
    path:     /list
    defaults: { _controller: AppBundle:Default:list }
default_form:
    path:     /form
    defaults: { _controller: AppBundle:Default:form }
user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: AppBundle:Default:delete }
