AppBundle\Entity\Blacklist:
    type: entity
    table: blacklist
    id:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: user_id
        blackListedId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: black_listed_id
    lifecycleCallbacks: {  }
