AppBundle\Entity\Chat:
    type: entity
    table: chat
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        from:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        to:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        message:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        sent:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
        recd:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
    lifecycleCallbacks: {  }
