AppBundle\Entity\Concert:
    type: entity
    table: concert
    id:
        concertId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: concert_id
            generator:
                strategy: IDENTITY
    fields:
        concertLibel:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: concert_libel
    lifecycleCallbacks: {  }
