AppBundle\Entity\Covoit:
    type: entity
    table: covoit
    id:
        covoitId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: covoit_id
            generator:
                strategy: IDENTITY
    fields:
        concertId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: concert_id
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        dateDepart:
            type: datetime
            nullable: false
            column: date_depart
        dateRetour:
            type: datetime
            nullable: false
            column: date_retour
        price:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        villeId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ville_id
    lifecycleCallbacks: {  }
