AppBundle\Entity\Forum:
    type: entity
    table: forum
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        date:
            type: datetime
            nullable: true
        userLogin:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
            column: user_login
    lifecycleCallbacks: {  }
