AppBundle\Entity\ListBook:
    type: entity
    table: list_book
    id:
        listId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: list_id
        bookId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: book_id
    lifecycleCallbacks: {  }
