AppBundle\Entity\RefBook:
    type: entity
    table: ref_book
    id:
        bookId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: book_id
            generator:
                strategy: IDENTITY
    fields:
        bookLibel:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: book_libel
    lifecycleCallbacks: {  }
