AppBundle\Entity\RefCategorie:
    type: entity
    table: ref_categorie
    id:
        categorieId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: categorie_id
            generator:
                strategy: IDENTITY
    fields:
        categorieLibel:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: categorie_libel
        mainCategorieId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: main_categorie_id
    lifecycleCallbacks: {  }
