AppBundle\Entity\RefHair:
    type: entity
    table: ref_hair
    id:
        hairId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: hair_id
            generator:
                strategy: IDENTITY
    fields:
        hairLibel:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
            column: hair_libel
    lifecycleCallbacks: {  }
