AppBundle\Entity\RefMailState:
    type: entity
    table: ref_mail_state
    id:
        mailStateId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: mail_state_id
            generator:
                strategy: IDENTITY
    fields:
        mailStateLibel:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
            column: mail_state_libel
    lifecycleCallbacks: {  }
