AppBundle\Entity\RefMainCategorie:
    type: entity
    table: ref_main_categorie
    id:
        mainCategorieId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: main_categorie_id
            generator:
                strategy: IDENTITY
    fields:
        mainCategorieLibel:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
            column: main_categorie_libel
    lifecycleCallbacks: {  }
