AppBundle\Entity\RefState:
    type: entity
    table: ref_state
    id:
        refStateId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ref_state_id
            generator:
                strategy: IDENTITY
    fields:
        stateLibel:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
            column: state_libel
    lifecycleCallbacks: {  }
