AppBundle\Entity\RefStyle:
    type: entity
    table: ref_style
    id:
        styleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: style_id
            generator:
                strategy: IDENTITY
    fields:
        styleLibel:
            type: string
            nullable: false
            length: 35
            options:
                fixed: false
            column: style_libel
    lifecycleCallbacks: {  }
