AppBundle\Entity\User:
    type: entity
    table: user
    id:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: user_id
            generator:
                strategy: IDENTITY
    fields:
        userLogin:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: user_login
        userPwd:
            type: string
            nullable: true
            length: 35
            options:
                fixed: false
            column: user_pwd
        roleId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: role_id
        userMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: user_mail
    lifecycleCallbacks: {  }
