AppBundle\Entity\Ville:
    type: entity
    table: ville
    id:
        villeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ville_id
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        codePostal:
            type: integer
            nullable: true
            length: 5
            options:
                unsigned: false
            column: code_postal
    lifecycleCallbacks: {  }
