<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class News extends \AppBundle\Entity\News implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsTitre', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsContenu', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsDate', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsTypeId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsMediaUrl', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsPhotoUrl');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsTitre', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsContenu', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsDate', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsTypeId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsMediaUrl', '' . "\0" . 'AppBundle\\Entity\\News' . "\0" . 'newsPhotoUrl');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (News $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNewsId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getNewsId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsId', array());

        return parent::getNewsId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsTitre($newsTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsTitre', array($newsTitre));

        return parent::setNewsTitre($newsTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsTitre', array());

        return parent::getNewsTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsContenu($newsContenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsContenu', array($newsContenu));

        return parent::setNewsContenu($newsContenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsContenu', array());

        return parent::getNewsContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsDate($newsDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsDate', array($newsDate));

        return parent::setNewsDate($newsDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsDate', array());

        return parent::getNewsDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsTypeId($newsTypeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsTypeId', array($newsTypeId));

        return parent::setNewsTypeId($newsTypeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsTypeId', array());

        return parent::getNewsTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsMediaUrl($newsMediaUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsMediaUrl', array($newsMediaUrl));

        return parent::setNewsMediaUrl($newsMediaUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsMediaUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsMediaUrl', array());

        return parent::getNewsMediaUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewsPhotoUrl($newsPhotoUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewsPhotoUrl', array($newsPhotoUrl));

        return parent::setNewsPhotoUrl($newsPhotoUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewsPhotoUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewsPhotoUrl', array());

        return parent::getNewsPhotoUrl();
    }

}
