<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Link extends \AppBundle\Entity\Link implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'expediteurId', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'destinataireId', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'modificationDate');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'expediteurId', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'destinataireId', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Link' . "\0" . 'modificationDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Link $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setExpediteurId($expediteurId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpediteurId', array($expediteurId));

        return parent::setExpediteurId($expediteurId);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpediteurId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getExpediteurId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpediteurId', array());

        return parent::getExpediteurId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinataireId($destinataireId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinataireId', array($destinataireId));

        return parent::setDestinataireId($destinataireId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinataireId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getDestinataireId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinataireId', array());

        return parent::getDestinataireId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setModificationDate($modificationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModificationDate', array($modificationDate));

        return parent::setModificationDate($modificationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getModificationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModificationDate', array());

        return parent::getModificationDate();
    }

}
