<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mail extends \AppBundle\Entity\Mail implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailId', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailContent', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailExpediteur', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailDestinataire', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailDate', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailStateId', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailboxId');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailId', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailContent', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailExpediteur', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailDestinataire', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailDate', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailStateId', '' . "\0" . 'AppBundle\\Entity\\Mail' . "\0" . 'mailboxId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mail $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMailId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMailId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailId', array());

        return parent::getMailId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailContent($mailContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailContent', array($mailContent));

        return parent::setMailContent($mailContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailContent', array());

        return parent::getMailContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailExpediteur($mailExpediteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailExpediteur', array($mailExpediteur));

        return parent::setMailExpediteur($mailExpediteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailExpediteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailExpediteur', array());

        return parent::getMailExpediteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailDestinataire($mailDestinataire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailDestinataire', array($mailDestinataire));

        return parent::setMailDestinataire($mailDestinataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailDestinataire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailDestinataire', array());

        return parent::getMailDestinataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailDate($mailDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailDate', array($mailDate));

        return parent::setMailDate($mailDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailDate', array());

        return parent::getMailDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailStateId($mailStateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailStateId', array($mailStateId));

        return parent::setMailStateId($mailStateId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailStateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailStateId', array());

        return parent::getMailStateId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailboxId($mailboxId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailboxId', array($mailboxId));

        return parent::setMailboxId($mailboxId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailboxId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailboxId', array());

        return parent::getMailboxId();
    }

}
