<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Article extends \AppBundle\Entity\Article implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artLibel', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'categorieId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artDescription', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'refStateId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPrice', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artDate', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPhotoUrl', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artColour', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPoids', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artTaille', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artMarque', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'livrePoste', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'livreSurplace', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artStateId');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artLibel', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'categorieId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artDescription', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'refStateId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPrice', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artDate', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPhotoUrl', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artColour', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artPoids', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artTaille', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artMarque', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'livrePoste', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'livreSurplace', '' . "\0" . 'AppBundle\\Entity\\Article' . "\0" . 'artStateId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Article $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getArtId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getArtId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtId', array());

        return parent::getArtId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtLibel($artLibel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtLibel', array($artLibel));

        return parent::setArtLibel($artLibel);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtLibel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtLibel', array());

        return parent::getArtLibel();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieId($categorieId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieId', array($categorieId));

        return parent::setCategorieId($categorieId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieId', array());

        return parent::getCategorieId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDescription($artDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDescription', array($artDescription));

        return parent::setArtDescription($artDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDescription', array());

        return parent::getArtDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefStateId($refStateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefStateId', array($refStateId));

        return parent::setRefStateId($refStateId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefStateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefStateId', array());

        return parent::getRefStateId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPrice($artPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPrice', array($artPrice));

        return parent::setArtPrice($artPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPrice', array());

        return parent::getArtPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtDate($artDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtDate', array($artDate));

        return parent::setArtDate($artDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtDate', array());

        return parent::getArtDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', array($userId));

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPhotoUrl($artPhotoUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPhotoUrl', array($artPhotoUrl));

        return parent::setArtPhotoUrl($artPhotoUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPhotoUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPhotoUrl', array());

        return parent::getArtPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtColour($artColour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtColour', array($artColour));

        return parent::setArtColour($artColour);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtColour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtColour', array());

        return parent::getArtColour();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtPoids($artPoids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtPoids', array($artPoids));

        return parent::setArtPoids($artPoids);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtPoids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtPoids', array());

        return parent::getArtPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtTaille($artTaille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtTaille', array($artTaille));

        return parent::setArtTaille($artTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtTaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtTaille', array());

        return parent::getArtTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtMarque($artMarque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtMarque', array($artMarque));

        return parent::setArtMarque($artMarque);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtMarque', array());

        return parent::getArtMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivrePoste($livrePoste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivrePoste', array($livrePoste));

        return parent::setLivrePoste($livrePoste);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivrePoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivrePoste', array());

        return parent::getLivrePoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivreSurplace($livreSurplace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivreSurplace', array($livreSurplace));

        return parent::setLivreSurplace($livreSurplace);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivreSurplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivreSurplace', array());

        return parent::getLivreSurplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtStateId($artStateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtStateId', array($artStateId));

        return parent::setArtStateId($artStateId);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtStateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtStateId', array());

        return parent::getArtStateId();
    }

}
