<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLogin', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPwd', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userGender', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userSubscribeDate', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roleId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLastConnexion', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userBirth', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'eyesId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'originId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userDescription', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLightDescription', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userCity', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userZipcode', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPhotoUrl', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userAlcohol', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userSmoke', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userTattoo', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userDrugs', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'styleId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'hairId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'lookId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPiercing', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userProfession', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userMusic', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPoids', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userTaille', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'weekUser', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userMail', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userValid', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'listId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'villeId');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLogin', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPwd', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userGender', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userSubscribeDate', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roleId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLastConnexion', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userBirth', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'eyesId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'originId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userDescription', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userLightDescription', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userCity', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userZipcode', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPhotoUrl', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userAlcohol', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userSmoke', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userTattoo', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userDrugs', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'styleId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'hairId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'lookId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPiercing', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userProfession', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userMusic', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userPoids', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userTaille', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'weekUser', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userMail', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'userValid', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'listId', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'villeId');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', array());

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLogin($userLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLogin', array($userLogin));

        return parent::setUserLogin($userLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLogin', array());

        return parent::getUserLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPwd($userPwd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPwd', array($userPwd));

        return parent::setUserPwd($userPwd);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPwd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPwd', array());

        return parent::getUserPwd();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserGender($userGender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserGender', array($userGender));

        return parent::setUserGender($userGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserGender', array());

        return parent::getUserGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserSubscribeDate($userSubscribeDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserSubscribeDate', array($userSubscribeDate));

        return parent::setUserSubscribeDate($userSubscribeDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserSubscribeDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserSubscribeDate', array());

        return parent::getUserSubscribeDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleId($roleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleId', array($roleId));

        return parent::setRoleId($roleId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleId', array());

        return parent::getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLastConnexion($userLastConnexion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLastConnexion', array($userLastConnexion));

        return parent::setUserLastConnexion($userLastConnexion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLastConnexion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLastConnexion', array());

        return parent::getUserLastConnexion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserBirth($userBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserBirth', array($userBirth));

        return parent::setUserBirth($userBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserBirth', array());

        return parent::getUserBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setEyesId($eyesId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEyesId', array($eyesId));

        return parent::setEyesId($eyesId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEyesId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEyesId', array());

        return parent::getEyesId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginId($originId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginId', array($originId));

        return parent::setOriginId($originId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginId', array());

        return parent::getOriginId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDescription($userDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDescription', array($userDescription));

        return parent::setUserDescription($userDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDescription', array());

        return parent::getUserDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserLightDescription($userLightDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserLightDescription', array($userLightDescription));

        return parent::setUserLightDescription($userLightDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserLightDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserLightDescription', array());

        return parent::getUserLightDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCity($userCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCity', array($userCity));

        return parent::setUserCity($userCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCity', array());

        return parent::getUserCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserZipcode($userZipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserZipcode', array($userZipcode));

        return parent::setUserZipcode($userZipcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserZipcode', array());

        return parent::getUserZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPhotoUrl($userPhotoUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPhotoUrl', array($userPhotoUrl));

        return parent::setUserPhotoUrl($userPhotoUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPhotoUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPhotoUrl', array());

        return parent::getUserPhotoUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserAlcohol($userAlcohol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserAlcohol', array($userAlcohol));

        return parent::setUserAlcohol($userAlcohol);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserAlcohol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserAlcohol', array());

        return parent::getUserAlcohol();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserSmoke($userSmoke)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserSmoke', array($userSmoke));

        return parent::setUserSmoke($userSmoke);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserSmoke()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserSmoke', array());

        return parent::getUserSmoke();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserTattoo($userTattoo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserTattoo', array($userTattoo));

        return parent::setUserTattoo($userTattoo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserTattoo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserTattoo', array());

        return parent::getUserTattoo();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserDrugs($userDrugs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserDrugs', array($userDrugs));

        return parent::setUserDrugs($userDrugs);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserDrugs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserDrugs', array());

        return parent::getUserDrugs();
    }

    /**
     * {@inheritDoc}
     */
    public function setStyleId($styleId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStyleId', array($styleId));

        return parent::setStyleId($styleId);
    }

    /**
     * {@inheritDoc}
     */
    public function getStyleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStyleId', array());

        return parent::getStyleId();
    }

    /**
     * {@inheritDoc}
     */
    public function setHairId($hairId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHairId', array($hairId));

        return parent::setHairId($hairId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHairId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHairId', array());

        return parent::getHairId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLookId($lookId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLookId', array($lookId));

        return parent::setLookId($lookId);
    }

    /**
     * {@inheritDoc}
     */
    public function getLookId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLookId', array());

        return parent::getLookId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPiercing($userPiercing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPiercing', array($userPiercing));

        return parent::setUserPiercing($userPiercing);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPiercing()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPiercing', array());

        return parent::getUserPiercing();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserProfession($userProfession)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserProfession', array($userProfession));

        return parent::setUserProfession($userProfession);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserProfession()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserProfession', array());

        return parent::getUserProfession();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserMusic($userMusic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserMusic', array($userMusic));

        return parent::setUserMusic($userMusic);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserMusic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserMusic', array());

        return parent::getUserMusic();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPoids($userPoids)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPoids', array($userPoids));

        return parent::setUserPoids($userPoids);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPoids()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPoids', array());

        return parent::getUserPoids();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserTaille($userTaille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserTaille', array($userTaille));

        return parent::setUserTaille($userTaille);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserTaille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserTaille', array());

        return parent::getUserTaille();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeekUser($weekUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeekUser', array($weekUser));

        return parent::setWeekUser($weekUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeekUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeekUser', array());

        return parent::getWeekUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserMail($userMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserMail', array($userMail));

        return parent::setUserMail($userMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserMail', array());

        return parent::getUserMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserValid($userValid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserValid', array($userValid));

        return parent::setUserValid($userValid);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserValid', array());

        return parent::getUserValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setListId($listId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListId', array($listId));

        return parent::setListId($listId);
    }

    /**
     * {@inheritDoc}
     */
    public function getListId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListId', array());

        return parent::getListId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleId($villeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleId', array($villeId));

        return parent::setVilleId($villeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleId', array());

        return parent::getVilleId();
    }

}
